export const STAGES = [
  {
    id: "origen",
    costume: "student",
    place: "Florida, Camagüey, Cuba",
    title: "I was born here",
    body: "Florida, northwest of Camagüey. Town, heat, family. The line starts here. The rest is walking.",
  },
  {
    id: "escuela",
    costume: "student",
    place: "Childhood and adolescence",
    title: "A good student, many moves",
    body: "I moved often. Different secondary schools and countryside pre-university programs. Changing classrooms never broke the habit of studying.",
  },
  {
    id: "militar",
    costume: "soldier",
    place: "Cuba · mandatory military service",
    title: "Soldier",
    body: "I was a soldier. I stood guard. Before I ever administered a server, I learned how to last a night on my feet.",
  },
  {
    id: "universidad",
    costume: "uni",
    place: "University of Camagüey “Ignacio Agramonte Loynaz”",
    title: "Computer Engineering",
    body: "Faculty of Informatics and Exact Sciences. That is where the craft took shape — and so did my life: I met the mother of my son.",
  },
  {
    id: "padre",
    costume: "dad",
    place: "Fourth year",
    title: "I became a father",
    body: "The line split in two without breaking: study and raise a child. No sprint compares to an exam and a baby in the same week.",
  },
  {
    id: "grado",
    costume: "grad",
    place: "Fifth year",
    title: "I graduated",
    body: "Computer engineer. The cap is a drawing. The degree is not.",
  },
  {
    id: "economia",
    costume: "badge",
    place: "University of Camagüey · Economics Department",
    title: "Computer science specialist",
    body: "SQL Server and accounting applications. Campus numbers passed through my hands.",
    chips: ["SQL Server", "Accounting", "Internal systems"],
  },
  {
    id: "radares",
    costume: "badge",
    place: "2017 · six years · Camagüey",
    title: "Systems and network administrator",
    body: "National Radar Center, at the Camagüey Provincial Meteorology Center. Six years keeping up the network that watches the sky.",
    chips: ["Systems", "Networks", "Servers", "Radar"],
  },
  {
    id: "viaje",
    costume: "suitcase",
    place: "After the radars",
    title: "I emigrated to the United States",
    body: "One suitcase. Another country. The craft does not stay at the airport. It goes in the bag with everything else.",
  },
  {
    id: "oficios",
    costume: "hardhat",
    place: "United States · trades",
    title: "Hands that can do the work",
    body: "Remodeling and construction. Car attendant at Target. UPS delivery helper. An engineer who has carried boxes understands a system from the ground up.",
  },
  {
    id: "cocina",
    costume: "chef",
    place: "Wingstop · Cuban restaurant · Italian restaurant",
    title: "Cook",
    body: "Shifts, heat, tempo. A kitchen teaches the same lesson as a production incident: prioritize, do not freeze, deliver.",
  },
  {
    id: "solar",
    costume: "hardhat",
    place: "Solar farms · United States",
    title: "Keep the panel on the sun",
    body: "I work on solar tracking systems: the mechanics and the logic that make each row follow the sun through the day.",
    chips: ["Solar tracking", "Field work", "Systems"],
  },
  {
    id: "linux",
    costume: "linux",
    place: "The thread that never snapped",
    title: "Linux, open source, the craft as hobby",
    body: "I never unplugged. Linux and free software were the night workshop. I can be on a job site or in a kitchen and still be a sysadmin in my head.",
    chips: ["Linux", "Open source", "Systems", "Networks"],
  },
  {
    id: "cierre",
    costume: "linux",
    place: "Contact",
    title: "If this line fits",
    body: "Systems, networks, Linux, data, or technical field work. Write me.",
    email: "terrerov@gmail.com",
  },
];
